const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const code=s=>`<pre><button class="copy" type="button">Copy</button><code>${esc(s)}</code></pre>`;
const rows=window.CKA_DATA||[];
if(rows.length!==100) throw new Error(`CKA page data mismatch: ${rows.length}`);
const root=document.querySelector('#lessonRoot'), toc=document.querySelector('#toc');
root.innerHTML=rows.map(r=>`<article class="lesson ${r.cls}" data-page="${r.n}"><div class="lesson-top"><div><span class="page-no">PAGE ${String(r.n).padStart(3,'0')} / 100</span><span class="domain-pill">${esc(r.domain)} · ${r.weight}</span></div><label class="done-label"><input class="done" data-id="${r.n}" type="checkbox"> 完成本頁</label></div><h2>${String(r.n).padStart(3,'0')}. ${esc(r.title)}</h2><div class="grid two"><section><h3>這頁要拿到的能力</h3><ul><li>能在 30 秒內說出本題責任邊界與第一個 evidence。</li><li>能用 <code>-h</code> / <code>kubectl explain</code> / 官方文件定位正確欄位。</li><li>修完後用狀態＋功能測試驗證 end state。</li></ul></section><section class="cue"><h3>白話模型</h3><p>${esc(r.core)}</p></section></div><section><h3>考場辨識訊號</h3><p>看到「${esc(r.title.split('：')[0])}」相關症狀，先確認 host / context / namespace，再保留 evidence，最後才修改。</p></section><section><h3>Command Path｜先記流程，不背長指令</h3>${code(r.cmds)}</section><section class="lab"><h3>Hands-on Drill｜週末一定要動手</h3><p>${esc(r.drill)}</p><p class="why"><strong>目的：</strong>做完要能指出「哪個輸出證明你的結論」。</p></section><section><h3>Verification｜沒有驗證就不算做完</h3>${code(r.verify)}</section><section class="trap"><h3>最容易失分的地方</h3><p>${esc(r.traps)}</p></section><section class="docs"><h3>官方文件訓練</h3><p>搜尋關鍵字：<code>${esc(r.docs)}</code></p><a target="_blank" rel="noopener" href="${docUrl(r.domain)}">Open official docs →</a></section><section class="self"><h3>60 秒自我抽考</h3><ol><li>如果只能看一份 evidence，你先看哪個？為什麼？</li><li>哪兩個 verification 能證明 end state，而不是只證明 command 成功？</li></ol></section><div class="pager"><button data-home>目錄</button><button data-prev="${r.n}">← Prev</button><button data-next="${r.n}">Next →</button></div></article>`).join('');
toc.innerHTML=rows.map(r=>`<button class="toc-item ${r.cls}" data-go="${r.n}"><span>${String(r.n).padStart(3,'0')}</span>${esc(r.title)}</button>`).join('');
function docUrl(d){if(d.startsWith('Cluster'))return'https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/';if(d.startsWith('Workloads'))return'https://kubernetes.io/docs/concepts/workloads/';if(d.startsWith('Services'))return'https://kubernetes.io/docs/concepts/services-networking/';if(d==='Storage')return'https://kubernetes.io/docs/concepts/storage/';return'https://kubernetes.io/docs/tasks/debug/';}
const home=document.querySelector('#homeview'),pane=document.querySelector('#lessonPane'),lessons=[...document.querySelectorAll('.lesson')],dones=[...document.querySelectorAll('.done')];let current=0;
function updateProgress(){const n=dones.filter(x=>x.checked).length;document.querySelector('#progress').textContent=`${n} / 100 completed`;}
dones.forEach(cb=>{cb.checked=localStorage.getItem('cka100-'+cb.dataset.id)==='1';cb.addEventListener('change',()=>{localStorage.setItem('cka100-'+cb.dataset.id,cb.checked?'1':'0');updateProgress();});});updateProgress();
function show(n){current=Math.max(1,Math.min(100,+n));home.classList.add('hidden');pane.classList.remove('hidden');lessons.forEach(x=>x.classList.toggle('active',+x.dataset.page===current));history.replaceState(null,'','#p'+current);window.scrollTo({top:document.querySelector('.toc-shell').offsetTop-58,behavior:'smooth'});}function showHome(){current=0;pane.classList.add('hidden');home.classList.remove('hidden');history.replaceState(null,'',location.pathname);}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-go]'))show(b.dataset.go);if(b.matches('[data-home]')||b.id==='homeBtn')showHome();if(b.matches('[data-prev]')&&+b.dataset.prev>1)show(+b.dataset.prev-1);if(b.matches('[data-next]')&&+b.dataset.next<100)show(+b.dataset.next+1);if(b.id==='prevBtn'&&current>1)show(current-1);if(b.id==='nextBtn'&&current<100)show(current+1);if(b.classList.contains('copy')){await navigator.clipboard.writeText(b.parentElement.querySelector('code').innerText);const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,700);}});
document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.toc-item').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none');});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(e.key==='ArrowRight'&&current<100)show(current+1);if(e.key==='ArrowLeft'&&current>1)show(current-1);if(e.key==='Escape')showHome();});
if(location.hash.match(/^#p\d+$/))show(parseInt(location.hash.slice(2)));